"""Agrega tabla curso y relacion curso_id en matricula

Revision ID: 07774151c0bb
Revises: 976db84b28ea
Create Date: 2025-10-04 22:42:31.608796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07774151c0bb'
down_revision = '976db84b28ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('matricula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curso_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('matricula_estudiante_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('fk_matricula_curso', 'curso', ['curso_id'], ['id'])
        batch_op.create_foreign_key('fk_matricula_estudiante', 'estudiante', ['estudiante_id'], ['id'])
        batch_op.drop_column('curso')

    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.alter_column('estudiante_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('pago_estudiante_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'estudiante', ['estudiante_id'], ['id'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pago_estudiante_id_fkey'), 'estudiante', ['estudiante_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('estudiante_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('matricula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curso', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint('fk_matricula_estudiante', type_='foreignkey')
        batch_op.drop_constraint('fk_matricula_curso', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('matricula_estudiante_id_fkey'), 'estudiante', ['estudiante_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('curso_id')

    op.drop_table('curso')
    # ### end Alembic commands ###
