"""Agrega relación docente_id en curso

Revision ID: 31e0cae6de7c
Revises: 07774151c0bb
Create Date: 2025-10-05 23:54:25.798335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e0cae6de7c'
down_revision = '07774151c0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('documento', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docente_id', sa.Integer(), nullable=True))
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('curso_nombre_key'), type_='unique')
        batch_op.create_foreign_key(None, 'docente', ['docente_id'], ['id'])

    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuario_id')

    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('curso_nombre_key'), ['nombre'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('docente_id')

    op.drop_table('docente')
    # ### end Alembic commands ###
